run:
  timeout: 5m
  tests: true
linters:
  enable:
    - govet
    - revive
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - gocritic
    - gofmt
    - goimports

linters-settings:
  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: exported
        arguments: ["disable"]
  gocritic:
    enable-all: false
    enabled-checks:
      - appendCombine
      - rangeValCopy
      - truncateCmp
      - sloppyReassign
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - revive
