version: "3.9"

services:
  relay:
    build:
      context: .
    image: intratun:latest
    command:
      - relay
      - --listen=:8080
      - --metrics=:9090
      - --agents=intra:changeme
      - --acl-allow=^.*:443$
    environment:
      - TZ=UTC
    expose:
      - "8080"
    ports:
      - "9090:9090"
    networks:
      - intratun

  caddy:
    image: caddy:2.8
    depends_on:
      - relay
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - intratun

  agent:
    image: intratun:latest
    command:
      - agent
      - --relay=ws://relay:8080/tunnel
      - --id=intra
      - --token=changeme
      - --dial-timeout-ms=5000
      - --max-frame=32768
    depends_on:
      - relay
    networks:
      - intratun

networks:
  intratun: {}
