version: "3.9"

services:
  relay:
    build:
      context: .
    image: intratun:latest
    command:
      - relay
      - --proxy-listen=:8080
      - --secure-listen=:8443
      - --socks-listen=:1080
      - --agents=intra:changeme
      - --acl-allow=^.*:443$
      - --acme-host=relay.example.com
      - --acme-email=ops@example.com
      - --acme-cache=/var/lib/intratun/acme
    environment:
      - TZ=UTC
    volumes:
      - ./acme-cache:/var/lib/intratun/acme
    ports:
      - "8080:8080"   # HTTP CONNECT
      - "8443:8443"   # WSS, dashboard, metrics
      - "1080:1080"   # Optional SOCKS5
    networks:
      - intratun

  agent:
    image: intratun:latest
    profiles:
      - agent
    command:
      - agent
      - --relay=wss://relay.example.com:8443/tunnel
      - --id=intra
      - --token=changeme
      - --dial-timeout-ms=5000
    environment:
      - TZ=UTC
    extra_hosts:
      - "relay.example.com:host-gateway" # adjust or remove depending on DNS setup
    networks:
      - intratun

networks:
  intratun: {}
