// Code generated by scripts/sync-version.mjs; DO NOT EDIT.
<<<<<<< HEAD
<<<<<<< HEAD
export const FRONTEND_VERSION = "0.1.0+build.49.87617da";
=======
export const FRONTEND_VERSION = "0.1.0+build.45.36ce936";
>>>>>>> 15a3e3f (fix visual in dashboard)
=======
export const FRONTEND_VERSION = "0.1.0+build.46.15a3e3f";
>>>>>>> parent of 2d1f96f (create signal for write done on agent and relay)
